-- DCS: Mi-8MTV2 Complete English (Black) Cockpit Mod v1.7.1 by Devrim.

livery = 
{
	{"mirror_mi8", 0,					"mirrors", true};
    {"Add_Blocks", 0,					"cockpit_mi-8mtv3_add_block", false};
    {"BCKWALL-01", 0,					"cockpit_mi-8mtv3_cab", false};
    {"BCKWALL-01", 2,					"cockpit_mi-8mtv3_cab_spec", false};
    {"CL-APP-BTN-ALTOFF", 0,			"mi8mtv-cpt-cl", false};
    {"CL-APP-BTN-ALTON", 0,				"mi8mtv-cpt-cl", false};
    {"CL-APP-BTN-DIROFF", 0,			"mi8mtv-cpt-cl", false};
    {"CL-APP-BTN-DIRON", 0,				"mi8mtv-cpt-cl", false};
    {"CL-APP-BTN-KTON", 0,				"mi8mtv-cpt-cl", false};
    {"Dashboards", 0,					"cockpit_mi-8mtv3_dash1", false};
    {"Dashboards", 2,					"cockpit_mi-8mtv3_dash1_spec", false};
    {"INSTR-AGB-SCALE_LIGHT_CENTER", 0,	"mi8mtv-cpt-pnl-base", false};
    {"LIGHT_LEFT_ record", 0,			"cockpit_mi-8mtv3_panels2", false};
    {"MI8-CPT-FLOOR-01", 0,				"mi8mtv-cpt-floor-01", false};
    {"MI8MTV-lamp", 0,					"mi8mtv-cpt-cl", false};
    {"MI8MTV-lamp_D_N", 0,				"mi8mtv-cpt-cl", false};
    {"Material #14", 0,					"cockpit_mi-8mtv3_dev2", false};
    {"Material #28", 0,					"cockpit_mi-8mtv3_dash1", false};
    {"Material #28", 2,					"cockpit_mi-8mtv3_dash1_spec", false};
    {"Material #29", 0,					"cockpit_mi-8mtv3_dev2", false};
    {"Material #31", 0,					"cockpit_mi-8mtv3_dev3", false};
    {"Material #32", 0,					"cockpit_mi-8mtv3_central_inscr", false};
    {"Material #33", 0,					"cockpit_mi-8mtv3_dev3", false};
    {"Material #34", 0,					"cockpit_mi-8mtv3_central_inscr", false};
    {"Material #35", 0,					"cockpit_mi-8mtv3_central_inscr", false};
    {"PKV", 0,							"cockpit_mi-8mtv3_pkv", false};
    {"PNL-01_LIGHT_CENTER", 0,			"cockpit_mi-8mtv3_panels1", false};
    {"PNL-01_LIGHT_LEFT", 0,			"cockpit_mi-8mtv3_panels1", false};
    {"PNL-01_LIGHT_RIGHT", 0,			"cockpit_mi-8mtv3_panels1", false};
    {"PNL-01_LIGHT_RIGHT_GRP2", 0,		"cockpit_mi-8mtv3_panels1", false};
    {"PNL-020_LIGHT_CENTER", 0,			"cockpit_mi-8mtv3_panels2", false};
    {"PNL-020_LIGHT_LEFT", 0,			"cockpit_mi-8mtv3_panels2", false};
    {"PNL-020_LIGHT_LEFT_GRP2", 0,		"cockpit_mi-8mtv3_panels2", false};
    {"PNL-020_LIGHT_RIGHT", 0,			"cockpit_mi-8mtv3_panels2", false};
    {"PNL-BASE", 0,						"mi8mtv-cpt-pnl-base", false};
    {"PNL-BASE5", 0,					"mi8mtv-cpt-pnl-base", false};
    {"PNL-BASE_LIGHT_LEFT", 0,			"mi8mtv-cpt-pnl-base", false};
    {"PitThr", 0,						"cockpit_mi-8mtv3_pitthr", false};
    {"PitThr", 2,						"cockpit_mi-8mtv3_pitthr", false};
    {"STICK-01", 0,						"mi8mtv-cpt-stick-01", false};
    {"Weapon Lamp", 0,					"cockpit_mi-8mtv3_dev2", false};
    {"central inscr", 0,				"cockpit_mi-8mtv3_central_inscr", false};
    {"dev3_ move namber R800", 0,		"cockpit_mi-8mtv3_dev3", false};
    {"dev_01_LIGHT_5_5", 0,				"cockpit_mi-8mtv3_dev1", false};
    {"dev_01_LIGHT_CENTER", 0,			"cockpit_mi-8mtv3_dev1", false};
    {"dev_01_LIGHT_LEFT", 0,			"cockpit_mi-8mtv3_dev1", false};
    {"dev_01_LIGHT_RIGHT", 0,			"cockpit_mi-8mtv3_dev1", false};
    {"dev_01_LIGHT_RIGHT_5_5", 0,		"cockpit_mi-8mtv3_dev1", false};
    {"dev_02_LIGHT_5_5", 0,				"cockpit_mi-8mtv3_dev2", false};
    {"dev_02_LIGHT_CENTER", 0,			"cockpit_mi-8mtv3_dev2", false};
    {"dev_02_LIGHT_LEFT", 0,			"cockpit_mi-8mtv3_dev2", false};
    {"dev_02_LIGHT_RIGHT", 0,			"cockpit_mi-8mtv3_dev2", false};
    {"dev_03_LIGHT_LEFT", 0,			"cockpit_mi-8mtv3_dev3", false};
    {"dev_03_NO_LIGHT_LEFT", 0,			"cockpit_mi-8mtv3_dev3", false};
    {"top_elements", 0,					"cockpit_mi-8mtv3_top_elem", false};
}